cortexapps/backstage-plugin

- package.json
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/CortexComponentsTable/CortexComponentsTable.tsx
- src/components/CortexComponentsTable/CortexScorecardScoresColumn.tsx
- src/components/CortexComponentsTable/index.ts
- src/components/CortexFetchComponent/CortexFetchComponent.tsx
- src/components/Gauge/Gauge.tsx
- src/components/Gauge/index.ts
- src/components/Scorecards/ScorecardCard/ScorecardCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableRow.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableRowDetails.tsx
- src/components/Scorecards/ScorecardsFetchComponent/CortexFetchComponent.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardsPage.test.tsx
- src/plugin.ts
- src/routes.ts
- yarn.lock
Major changes:
* Use new stable Cortex endpoints
* Send entire set of entities for Cortex sync (to build up full graph of dependencies, systems, etc)
Small UI fixes:
* Use standard Gauge component (TODO: need to merge back upstream to Backstage)
* Deep linking to components and within plugin
* Show errors for failing scorecard rules
> Use stable API endpoints

- README.md
- package.json
- src/components/CortexScorecardWidget/CortexScorecardWidget.test.tsx
- src/components/CortexScorecardWidget/CortexScorecardWidget.tsx
- src/components/CortexScorecardWidget/index.ts
- src/components/EntityPage/EntityPage.tsx
- src/components/EntityPage/EntityScorecardsCard.tsx
- src/components/EntityPage/EntityScorecardsCardRow.tsx
- src/components/ScorecardServiceRefLink/ScorecardServiceRefLink.tsx
- src/components/ScorecardServiceRefLink/index.ts
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableRow.tsx
- src/index.ts
- src/plugin.ts
Backstage component widget that shows an overview of scorecards for a service component and the service's scores. Clicking on a scorecard takes you to that service's detailed scorecard page.
The links for the scorecards in a service component's Cortex catalog tab have also been updated to take you to that service's detailed scorecard page instead of the overall scorecard page.
> Fix [#1]()
> Backstage component scorecard widget

- package.json
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/RuleResultDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardResultDetails.tsx
Show failure messages for rules in scorecard sections in entity
> Fix [#1]()
> CET-483 show failure messages for rules in scorecard section

- package.json
- src/components/CortexScorecardWidget/CortexScorecardWidget.tsx
- src/components/EntityPage/EntityPage.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
ScorecardWidget takes users to the Entity page for selected scorecard: 
> Fix [#1]()
> have scorecard widget take users to entity page for selected scorecards

- package.json
- src/components/EntityPage/EntityScorecardsCardRow.tsx
- src/components/FilterCard/Filters.tsx
- src/components/Gauge/Gauge.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeFilterCard/InitiativeFilterCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTableRow.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/PassingComponentsTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableHeader.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableRow.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServicePage.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceProgress.tsx
- src/components/SystemPage/SystemPage.tsx
- src/components/SystemPage/SystemPageRow.tsx
- src/components/SystemPage/SystemPageRowDetails.tsx
- src/utils/URLUtils.ts
Multiple updates: 
AllScorecards and Bird's Eye Report tables have 15% width for first column (the column with the names) 
Updated Gauge styling so that it doesn't get squished even when screen is tiny:
Added level info throughout to Scorecards Row when ladders exist for the Scorecard (Need to verify Systems page here - I wasn't sure how to get to it):
Use rule names if they exist in Initiatives filters: 
Link to open in Cortex from Single Scorecard details page (https://cortex1.atlassian.net/browse/CET-724 - Is this where they wanted it?)
Handled including component name if not default: https://cortex1.atlassian.net/browse/CET-726
> Fix [#1]()
> Various backstage updates

- package.json
- src/components/ReportsPage/HeatmapPage/HeatmapPage.test.tsx
- src/components/ReportsPage/HeatmapPage/LevelsInfoCell.tsx
Fixes the formatting of level-driven service lists for the heatmap report
[CET-813](https://cortex1.atlassian.net/browse/CET-813)
> fix: fix level info cell list formatting

- package.json
- src/components/Initiatives/InitiativeCard/InitiativeCard.tsx
- src/components/ListCard/ListCard.tsx
- src/components/Scorecards/ScorecardCard/ScorecardCard.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardsPage.test.tsx
Adds a "Show more" / "Show less" to long scorecard descriptions on the Scorecards page.
N/A
> fix: add collapse/expand to scorecard description

- package.json
- src/components/Scorecards/ScorecardDetailsPage/ScorecardFilterCard/ScorecardFilterCard.tsx
- src/utils/hooks.ts
Turn group/system/etc filters from `O(#services * #groups)` to `O(#groups)` every time there's an update to one of the filters.
> Fix [#1]()
> [CET-912] Optimize group/system filters

- package.json
- src/components/FilterCard/Filters.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeFilterCard/InitiativeFilterCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetailsPage.test.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardFilterCard/ScorecardFilterCard.tsx
- src/utils/hooks.ts
Scorecards and initiatives that have >10 rules see a dropdown for filtering by rule. Currently, selecting an option causes a JavaScript error to be thrown. This PR fixes the underlying issue, allowing the filter to be properly applied.
**Before**
https://user-images.githubusercontent.com/3069614/173956699-9c4f999a-97fe-40c6-ab77-cf03dfd6d4b1.mov
**After**
https://user-images.githubusercontent.com/3069614/173956833-2777b722-e04e-4969-b193-865ddc9d8250.mov
N/A
> fix: fix error filtering rules by dropdown

- README.md
- package.json
- src/components/Scorecards/ScorecardsPage/ScorecardsPage.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServicePage.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceProgress.tsx
- src/utils/URLUtils.test.ts
- src/utils/URLUtils.ts
On Service Scorecards page, we expose a "View in Cortex" link to send users from backstage to the Cortex app. However, we currently only link to the cloud URL so self-hosted users are sent to a 404.
This PR allows users to optionally configure the frontend URL for the Cortex app so they can easily point the link to their own deployment.
Most of the credit for this PR goes to @jsundquist for opening the initial version of this in https://github.com/cortexapps/backstage-plugin/pull/84 -- I merely did some connecting of dots to ensure everything propagated through as expected.
https://github.com/cortexapps/backstage-plugin/pull/84
> feat: add support for self-hosted cortex links

- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/Common/PollingLinearGauge.tsx
- src/components/Common/PollingProgressBar.tsx
- src/components/SettingsPage/SettingsPage.test.tsx
- src/components/SettingsPage/SettingsSyncCard.tsx
- src/utils/HookUtils.ts
- src/utils/MathUtils.ts
Backstage entity sync is no longer synchronous. Clicking the button submits a job to the backend and shows an estimated progress bar. Users can only submit one sync at a time but they can see when the last sync occurred and cancel an ongoing sync.
> Fix [#1]()
> CET-1147 move backstage sync job to background task

- README.md
- config.d.ts
- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/components/SettingsPage/SettingsPage.test.tsx
- src/components/SettingsPage/SettingsSyncCard.tsx
When performing manual entity sync in the settings page, you can choose to use gzip to compress the entities by updating `app-config.yaml` with the parameter `syncWithGzip`. By default, this behavior is _not_ enabled since it requires users to update proxy settings.
> Fix [#1]()
> Support gzip in entity sync

- package.json
- src/components/DefaultEntityLink/DefaultEntityRefLink.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTable.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTableRow.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/InitiativeTableCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/PassingComponentsTable.tsx
- src/components/ReportsPage/AllScorecardsPage/AllScorecardsHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByService.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetailsPage.test.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetailsPage.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableCard.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServicePage.tsx
- src/utils/hooks.ts
> Backstage reports use tag for displaying a service row. Instead use the corresponding name of the service to display the row.
Note: we must keep the tag as the metadata.name so the entity can still be identified
> [CET-3001](https://cortex1.atlassian.net/browse/CET-3001)
[CET-3001]: https://cortex1.atlassian.net/browse/CET-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CET-3001 - Metadata.name showing as entity name in Backstage reports instead of metadata.title

- package.json
- src/api/types.ts
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRulesCard/ScorecardRuleRow.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRulesCard/ScorecardRulesCard.tsx
This PR exposes rule filters on the Scorecard details page alongside the rule. Rule filters for CQL and group inclusion/exclusion are accounted for.
See Scorecard detail page rule will be shown as the following if it is filtered out:
> Fix [#1]()
> [CET-2856] Add rule filters

- package.json
- src/components/CortexScorecardWidget/CortexScorecardWidget.tsx
At least one customer is navigating to an invalid URL due to a double slash (e.g. `/component/abcd/` => `/component/abcd//cortex?scorecard=123`). This PR adds a check for extra paranoia to not add a double slash.
N/A
> fix: handle trailing slash in path for Scorecard widget

- package.json
- src/api/CortexClient.ts
- src/components/Common/PollingLinearGauge.tsx
- src/components/SettingsPage/SyncCard.tsx
We're getting timeouts from our current job as of a month ago. So this PR will start sending chunked requests over instead, to improve fault tolerance of the sync job.
* Start chunking sync request into separate `POST`s 
* Fix bug where backend tasks at 100% but `IN_PROGRESS` keep `PollingProgressBar` in DOM
* Show loader when sending over Backstage entities, instead of frozen UI until the progress bar mounts
> [CET-4523] Break up Backstage sync into separate chunked requests

- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/components/CortexGroupActionItemsWidget/CortexGroupActionItemsWidget.test.tsx
- src/components/SettingsPage/SettingsPage.test.tsx
- src/components/SettingsPage/SyncCard.tsx
- yarn.lock
Give users the option to limit which entities are sent over to Cortex for the YAML conversion / sync -- we're sending way too much data for larger instances of Backstage, and this will give some configuration power back to the users if there's completely unused data being sent to Cortex.
Some additional refactors / cleanups:
* Ran prettier on `CortexClient.ts`
* Moved "custom mappings" application logic out of `CortexClient`
Depends on: https://github.com/cortexapps/backstage-plugin-extensions/pull/17
> Fix [#1]()
> [CET-4196] Optional filter to limit entities sent to Cortex

- CHANGELOG.md
- package.json
- src/api/CortexClient.test.ts
- src/api/CortexClient.ts
**REQUIRES BE PR** https://github.com/cortexapps/brain-backend/pull/5072
We use own headers in backstage plugin
```
'x-cortex-email': email ?? '',
'x-cortex-name': displayName ?? '',
```
but with non  ISO-8859-1 characters like `ğ` in user names it caused: 
```
index-cc953267.esm.js:449 TypeError: Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.
at CortexClient.fetchAuthenticated (index-cc953267.esm.js:444:1)
at async CortexClient.get (index-cc953267.esm.js:353:1)
at async eval (index-35f4277a.esm.js:2361:1)
```
Idea:
1. encode our headers on backstage-plugin
2. decode them on brain-brackend https://github.com/cortexapps/brain-backend/pull/5072
tested manually by adding headers like
``` …
```
> CET-6731   [Unity] User can't access the Backstage plugin interface

- CHANGELOG.md
- package.json
- src/components/Common/StatsItem.tsx
CET-6941
Fix for `Stats` component label color on light theme.
> CET-6941 Fix StatsItem color

- CHANGELOG.md
- package.json
- src/components/Homepage/HomepageInsightCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeFailingTab/InitiativeFailingTab.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativePassingTab/InitiativePassingTab.tsx
- src/components/ReportsPage/HeatmapPage/LevelsInfoCell.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByService.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRuleExemptionsTab/ScorecardRuleExemptionsTab.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsScoresTab/ScorecardsScoresTable.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServicePage.tsx
- src/utils/ComponentUtils.ts
- src/utils/hooks.ts
Requires https://github.com/cortexapps/brain-backend/pull/5313
1. Use correct `kind` and `namespace` when building Backstage Entity Refs.
2. Use full Entity Ref instead only our `codeTag` to properly identify entity and link within Backstage
> CET-7027 use full backstage ref

- CHANGELOG.md
- package.json
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceRuleRow.tsx
TODO: bump version before merge
[[CET-7368](https://cortex1.atlassian.net/browse/CET-7368)][Getyourguide] Rule violation being generated on on passing scorecard rule
Before
After
[CET-7368]: https://cortex1.atlassian.net/browse/CET-7368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CET-7368] Hide the failing message if rule is passing

- CHANGELOG.md
- package.json
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceRuleRow.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceRulesDetails.tsx
- src/utils/ScorecardRules.ts
TODO: bump version before merge
[[CET-7395](https://cortex1.atlassian.net/browse/CET-7395)] [GetYourGuide] Backstage plugin - Scorecard rule evaluation failure errors not rendering in Backstage
Before
After
[CET-7395]: https://cortex1.atlassian.net/browse/CET-7395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CET-7395] Show rule result error

- CHANGELOG.md
- package.json
- src/components/Common/Truncated.tsx
- src/components/ListCard/ListCard.tsx
- src/components/Scorecards/ScorecardCard/ScorecardCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataCard.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceHeader.tsx
[[CET-8100](https://cortex1.atlassian.net/browse/CET-8100)] [Peloton] Backstage plugin rendering Markdown as plain text
As a part of the feature, I created new component `Truncated` to wrap and truncate text by the number of lines.
Before:
After:
[CET-8100]: https://cortex1.atlassian.net/browse/CET-8100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CET-8100] [Peloton] Backstage plugin rendering Markdown as plain text

- CHANGELOG.md
- package.json
- src/api/types.ts
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.test.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataFilter.tsx
- src/components/Initiatives/InitiativesPage/InitiativesList.tsx
- src/utils/TestUtils.tsx
https://cortex1.atlassian.net/browse/CET-8301
Entity groups for initiatives are sent by brain-backend the same way as they are for scorecards, so I removed the unused attribute (entityGroups) from the model and added the new one (filter), then reused some logic from scorecards utils to print a correct text.
> CET-8301 Update backstage after initiative filter changes

- CHANGELOG.md
- package.json
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceRuleRow.tsx
https://cortex1.atlassian.net/browse/CET-8544
Text colors of rule description and rule query are swapped what makes the rule more readable.
> CET-8544 Swap rule description and rule query text colors

- src/components/ReportsPage/HeatmapPage/HeatmapUtils.ts
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
If we detect that the next click is the end of the line in regards to hierarchy then we apply a filter and group by entity so that we can view the list of entities for that item.
I think this can then be used for the same logic of "Everything owned by X".
> Add in entity click logic when in hierarchy mode

- CHANGELOG.md
- package.json
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
When in hierarchy mode we should disable the last item as it doesn't need to be clickable. Once we dive into entity view we can enable it.
> Fix disabling levels hierarchy breadcrumbs correctly

- CHANGELOG.md
- package.json
- src/components/Initiatives/InitiativeDetailsPage/InitativeFilterDialog/InitiativeFilterDialogUtils.ts
It was reported, opening initiative in backstage with filter applied (by email owner, who is not on the filter list), results in throwing an error.
Additional check is applied to verify if email provided in filter is on the list.
> CET-9977 Fix for opening initiative filtered by email owner who doesn't exist

- CHANGELOG.md
- package.json
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
[CET-9978] Error when viewing Bird's Eye Report in Backstage
Bird's Eye Report trowed an error when attempting to display heatmap with archived entity.
[CET-9978]: https://cortex1.atlassian.net/browse/CET-9978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CET-9978] Error when viewing Bird's Eye Report in Backstage

- CHANGELOG.md
- package.json
- src/components/Homepage/HomepageInsightCard.tsx
- src/components/Initiatives/InitiativeCard/InitiativeCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.test.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataCardUtils.ts
This partially reverts #183. Namely converting the Initiatives target date to local TZ.
Before this change, UTC-7 (shifted)
After this change, UTC-7 (not shifted)
After this change, UTC+2 (not shifted)
> [CET-9710] Initiative due date discrepancy between Cortex and Backstage

- CHANGELOG.md
- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/api/userInsightTypes.ts
- src/components/FilterCard/Filters.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitativeFilterDialog/InitiativeFilterDialogUtils.ts
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.test.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.tsx
- src/utils/hooks.ts
Added new filter to the Initiatives details page - my entities.
Based on new endpoint (`/api/backstage/v2/entities/my-entities`) action items are filtered to display only those which are owned by the user.
🚨 Needs to be released with https://github.com/cortexapps/brain-backend/pull/6940
> Initiatives filter - my entities

- CHANGELOG.md
- package.json
- src/components/ReportsPage/ProgressPage/ProgressPage.tsx
Currently selecting "Group by" Domain on Progress report is not supported by our backend - throwing 400.
This change adds guard on backstage-plugin level.
> CET-11302   [Adobe] Indicator for group by Domain in Historical Report

- .github/workflows/publish-gh-registry.yml
- README.md
- config.d.ts
- package.json
- scripts/add_publish_to_github_config.sh
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/components/SettingsPage/SettingsPage.test.tsx
- src/components/SettingsPage/SyncCard.tsx
Allows users to change the size of sync chunks via config. Notable helps to solve problem where users were getting a 413 request too large from the backstage server when attempting to send large entities.
example usage:
```
cortex:
syncWithGzip: true
syncChunkSize: 30
```
https://cortex1.atlassian.net/browse/CET-12628?atlOrigin=eyJpIjoiZGU3Y2Q4ZjQzMGE1NDI1Yzg4NTdlM2MxOTg2YWQ4ZmUiLCJwIjoiaiJ9
Tested against dev environment with chunk size of 3 and 63 entities, confirmed 21 chunk requests sent
> Add new syncChunkSize config value

- CHANGELOG.md
- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/utils/hooks.ts
CET-13421 Adobe performance with Backstage on Bird's Eye report
**Requires BE**: https://github.com/cortexapps/brain-backend/pull/8087
Changed fetching owners for entities to fetch only those for entities for which we have scores for scorecard.
> CET-13421 Adobe performance with Backstage on Bird's Eye report

- package.json
- src/index.ts
- src/plugin.ts
The HomepageInsightsCard seems is very useful, however having it exposed only in the predefined CortexHomepage is not Ideal as we can't customizing that specific page.
> feat: expose the HomepageInsightsCard, so I can be added to any page
