- package.json
- src/components/Gauge/Gauge.tsx
- src/components/ItemCardHeader/ItemCardHeader.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardFilterCard/ScorecardFilters.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataItem.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableRowDetails.tsx
- src/styles/styles.ts
For runtime differences in Backstage `ThemeProvider` schemas
> Add Fallback Palette

- package.json
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableCard.tsx
- src/components/SettingsPage/SettingsPage.tsx
- src/components/SettingsPage/SettingsSyncCard.tsx
- src/components/SettingsPage/index.ts
- yarn.lock
* Settings page to bring back manual sync
* No data message for `<ScorecardsTableCard>`
> Settings page

- package.json
- src/api/CortexClient.ts
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTable.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/InitiativeTableCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/PassingComponentsTable.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableCard.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardsPage.test.tsx
- yarn.lock
> Remove @backstage/core

- package.json
- yarn.lock
Bump @backstage/cli to 0.11.0
> Fix [#1]()
> CET-391 bump backstage/cli to 0.11.0

- src/components/Scorecards/ScorecardsPage/ScorecardsPage.tsx
Sort scorecards alphabetically
> Fix [#1]()
> CET-401 sort scorecards alphabetically

- .github/workflows/check-versions.yml
* Auto-message `#project-backstage` monday-friday for out of date / conflicting Backstage package versions
> Fix [#1]()
> [CET-388] Automated warnings for outdated Backstage dependencies

- package.json
- src/api/types.ts
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
- yarn.lock
* Also update custom data mapping type to support `any` values
> Fix [#1]()
> [CET-384] Remove average score from reports

- .gitignore
- package.json
- scripts/diff.patch
- scripts/download_backstage.sh
- scripts/run_branch.sh
- src/api/CortexClient.ts
- src/api/ExtensionApi.ts
- yarn.lock
* Also added a script to automate local development steps -- will later be used for e2e testing on CI as well
> Fix [#1]()
> [CET-393] Upgrade Backstage versions

- package.json
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
Removes the headers for the cells removed in this PR: https://github.com/cortexapps/backstage-plugin/commit/32c14fd34265196be4f674ef59903cb2743f873e
> Fix [#1]()
> removing the headers for the prev removed rows in the reports

- .eslintrc.js
- package.json
- rollup.config.js
- src/components/CortexPage/CortexPage.tsx
- src/components/DefaultEntityLink/DefaultEntityRefLink.tsx
- src/components/FilterCard/FilterCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardLaddersCard/ScorecardLaddersCard.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceNextRules.tsx
- yarn.lock
> eslint improvements to make my life better

- package.json
- src/components/SystemPage/SystemPage.tsx
- src/components/SystemPage/SystemPageRow.tsx
- src/components/SystemPage/SystemPageRowDetails.tsx
- src/index.ts
- src/plugin.ts
Add system tab with aggregate scorecard scores
> Fix [#1]()
> CET-381 add aggregate scorecard scores to the system view

- package.json
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/ReportsPage/AllScorecardsPage/AllScorecardsHeatmap.tsx
- src/components/ReportsPage/AllScorecardsPage/AllScorecardsPage.tsx
- src/components/ReportsPage/Common/HeaderTypeDropdown.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapCell.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapUtils.ts
- src/components/ReportsPage/HeatmapPage/LevelsInfoCell.tsx
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableHeader.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
- src/components/ReportsPage/ProgressPage/AggregatedScorecardProgress.tsx
- src/components/ReportsPage/ProgressPage/ProgressPage.tsx
- src/components/ReportsPage/ReportsPage.tsx
- src/utils/ScorecardLadderUtils.ts
- src/utils/strings.ts
Three report types
Levels driven report in Bird's eye with collapsible sections 
> Fix [#1]()
> CET 450 levels driven report and all scorecards report

- package.json
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardStatsCard/ScorecardStatsCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardStatsCard/StatsItem.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardStatsCard/index.ts
Stats in Scorecard details page that update as filters change
> Fix [#1]()
> Cet 555 scorecard stats

- package.json
- src/api/types.ts
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTable.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/InitiativeTableCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/PassingComponentsTable.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRulesCard/ScorecardRuleRow.tsx
> show prioritized rules + levels in initiatives

- package.json
- src/api/types.ts
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeStatsCard/InitiativeStatsCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeStatsCard/index.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataCard.tsx
Filtering details in initiatives for all cases: 
Stat for percent complete
> Fix [#1]()
> add initiatives filtering details to metadata section + add percent complete to stats card

- package.json
- src/components/EntityPage/EntityScorecardRules/EntityScorecardRules.tsx
- src/components/EntityPage/EntityScorecardsCard.tsx
- src/components/FilterCard/FilterCard.tsx
- src/components/FilterCard/Filters.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTable.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/PassingComponentsTable.tsx
- src/components/Initiatives/InitiativesPage/InitiativesPage.tsx
- src/components/ListCard/ListCard.tsx
- src/components/ReportsPage/Common/GroupByDropdown.tsx
- src/components/ReportsPage/Common/LookbackDropdown.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByService.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/ProgressPage/ProgressPage.tsx
- src/components/ReportsPage/ScorecardSelector.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardLaddersCard/ScorecardLaddersCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRulesCard/ScorecardRulesCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/RuleResultDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardResultDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableCard.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceProgress.tsx
- src/components/StatsCard/StatsCard.tsx
- src/components/SystemPage/SystemPage.tsx
- src/components/SystemPage/SystemPageRowDetails.tsx
- src/utils/ScorecardRules.ts
- fix keys to be unique throughout app
- use markdown in library item cards
- sort rules in Scorecard + Initiatives details page 
> Fix [#1]()
> fix keys throughout app, use markdown in library item cards, sort rules

- package.json
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
Add number of services to all scorecards report
> Fix [#1]()
> CET-470 add number of services to all scorecards report

- package.json
- src/api/CortexClient.ts
- src/plugin.ts
https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md
* Does not block requests for Backstage installations that doesn't explicitly block through middleware
> Fix [#1]()
> [CET-544] Support for auth middleware

- package.json
- yarn.lock
> Bump backstage-plugin-extenions

- package.json
- src/components/Common/SortDropdown.tsx
- src/components/CortexScorecardWidget/CortexScorecardWidget.test.tsx
- src/components/CortexScorecardWidget/CortexScorecardWidget.tsx
- src/components/EntityPage/EntityPage.tsx
- src/components/EntityPage/EntityScorecardOverview/EntityScorecardOverview.tsx
- src/components/EntityPage/EntityScorecardsCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/RuleResultDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardResultDetails.tsx
- src/index.ts
- src/utils/SearchUtils.ts
- src/utils/hooks.ts
You can also add a prop filter to the Scorecard widget for either the name, id, score. For example: 
<CortexScorecardWidget include={{names: ['scorecard'] }} excludeFilters={{ scores: [1]}} />
> Fix [#1]()
> add sort dropdown + search field to scorecard widget

- package.json
- src/components/EntityPage/EntityPage.tsx
- src/components/EntityPage/EntityScorecardDetails/EntityScorecardDetails.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceNextRules.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServicePage.tsx
* Was previously using `useEntity` inside the CortexPage under scorecards, in which no entity context exists
> Fix [#1]()
> [CET-653] Fix Entity Context Bug

- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceNextRules.tsx
Change 'Ladder Progress' to 'Level Progress' in Scorecard details view
- [ x ] Improvement (improves codebase without changing functionality)
> Change 'Ladder Progress' to 'Level Progress'

- package.json
- src/components/Gauge/Gauge.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableRow.tsx
- src/utils/types.test.ts
- src/utils/types.ts
* Fix font on Gauge text
* Show "humanized" refs for components in scorecard details page
> Fix [#1]()
> [CET-762] Fix Backstage UI/UX issues

- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/Initiatives/InitiativesPage.test.tsx
> CET-929 Splitting Initiatives & Initiatives With Scores P3/3

- README.md
> [CET-891] Add system page to README

- .github/CODEOWNERS
- package.json
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/FailingComponentsTable.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeTableCard/PassingComponentsTable.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardsTableCard/ScorecardsTableCard.tsx
Sorted first by num action items then alphabetically:
Default sorts by score but user can change that by clicking the column on the table that they want to sort. 
> Fix [#1]()
> Cet 1126 sort initiatives

- .gitignore
- package.json
- src/components/CortexPage/CortexPage.tsx
- yarn.lock
> feat: make `CortexPage` title and subtitle configurable

- README.md
Duplicate 8/9 instructions consolidated.
Bearer keyword added to Authorization instructions.
> Fix [#1]()
> Dedupe docs and add `Bearer` to Authorization instructions

- README.md
> Fix setup instructions in README

- README.md
> Auth add Bearer keyword

- package.json
- src/components/Initiatives/InitiativesPage/InitiativesPage.tsx
change the copy of the error message to read 'initiatives' instead of 'scorecards'
NOTE:  version in this PR conflicts with version bump in the dev workflow patches PR i have open: https://github.com/cortexapps/backstage-plugin/pull/75
Whichever one merges first wins the version!
for https://cortex1.atlassian.net/browse/CET-1319
> fix iniatives error message

- package.json
- src/components/EntityPage/EntityPage.test.tsx
- src/components/EntityPage/EntityPage.tsx
- src/components/EntityPage/EntityScorecardOverview/EntityScorecardOverview.test.tsx
- src/components/EntityPage/EntityScorecardRules/EntityScorecardRules.test.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapUtils.test.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetailsPage.test.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardStatsCard/ScorecardStatsCard.tsx
- src/components/StatsCard/StatsCard.tsx
- src/utils/TestUtils.tsx
See [CET-2313](https://cortex1.atlassian.net/browse/CET-2313) for details.
> Fix [#1]()
[CET-2313]: https://cortex1.atlassian.net/browse/CET-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase test coverage

- .github/CODEOWNERS
Ben is no longer an active developer on this project, so removing him from the codeowners.
N/A
> chore: remove ben from codeowners

- README.md
- config.d.ts
- package.json
- src/components/CortexPage/CortexPage.tsx
- src/components/EntityPage/EntityScorecardsCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataCard.tsx
- src/components/Initiatives/InitiativesPage/InitiativesList.tsx
- src/components/Initiatives/InitiativesPage/InitiativesPage.tsx
- src/components/ListCard/ListCard.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataCard.test.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataCard.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardList.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardsPage.tsx
Added search bar -- checks through name, desc, and filters 
Show search bar + sort dropdown and add state for no Scorecards based on query
Updated UI: Search bar + sort dropdown are below title 
Added hideSettings flag to fully hide the settings page from all users 
> Fix [#1]()
> lots of updates based on adobes feature requests

- package.json
- src/components/Common/SortDropdown.tsx
- src/components/EntityPage/EntityScorecardsCard.tsx
- src/components/Initiatives/InitiativeCard/InitiativeCard.tsx
- src/components/Initiatives/InitiativesPage/InitiativesList.tsx
- src/components/ListCard/ListCard.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardList.tsx
- Added sort dropdown to Scorecards page & updated search placeholder
- Updated search placeholder
- Added due date + sort dropdown to initiatives (not requested but I figured nice to have) 
> Fix [#1]()
> add sort dropdowns + update placeholder text

- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/SettingsPage/SettingsPage.tsx
- src/components/SettingsPage/SyncCard.tsx
- src/components/SettingsPage/SyncJobsTable.test.tsx
- src/components/SettingsPage/SyncJobsTable.tsx
New table in settings page to see status of historical Backstage <> Cortex sync jobs.
> Fix [#1]()
> [CET-2916] Historical sync job statuses

- config.d.ts
- package.json
> Fix flag type

- src/components/Common/CopyButton.tsx
- src/components/ReportsPage/AllScorecardsPage/AllScorecardsPage.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/components/Scorecards/ScorecardDetailsPage/CopyCsvButton.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetailsPage.test.tsx
- src/utils/WindowUtils.ts
- src/utils/collections.ts
Added button to scorecard details page. The button copies all the scores into CSV
> [4383] Add copy CSV functionality

- .github/pull_request_template.md
- CHANGELOG.md
Occasionally, customers ask what the changes are when they are interested in upgrading to a new version. In an ideal world, we would auto-generate the changelog (via [semantic-release](https://github.com/semantic-release/semantic-release) or similar) on changes, but I recently went through the exercise of enumerating changes since 2.0.0 and I think a simple but effective strategy for the time being is manually keeping track of the changes as we make them.
This PR adds the changelog since 2.0.0 to a new `CHANGELOG.md` file. Future PRs should also update this file with a description of their changes, as indicated by the updated PR template.
N/A
> chore: add changelog

- CHANGELOG.md
- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/api/types.ts
- src/components/CortexLayout/CortexLayout.tsx
- src/components/CortexPage/CortexPage.tsx
- src/components/Entitlements/ExpirationBanner.tsx
- src/components/Entitlements/ExpirationUtils.test.ts
- src/components/Entitlements/ExpirationUtils.ts
- src/utils/dates.ts
For banner messages mostly copy-pasted code from brain-app. 
Requires brain backend https://github.com/cortexapps/brain-backend/pull/4744
Both expiration and shutdown dates in past:
Expiration date in past and shutdown date today
Expiration date in pass but shutdown date in future
Expiration date today and shutdown date in future:
Expiration date in future < 14 days
Expiration date in future >14 days
TRIAL - expired
TRIAL - expiration date in past but shutdown in future
TRIAL - expiration in future, but always show banner
> CET-5850   [Backstage] Respects tenant end date

- src/api/CortexClient.ts
- src/api/types.ts
- src/components/ReportsPage/Common/GroupByDropdown.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
- src/components/ReportsPage/ProgressPage/ProgressPage.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetails.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRuleExemptionsTab/ScorecardRuleExemptionsTab.tsx
Few minor changes after merging Initiatives page revamp.
BE PR needed to run this: https://github.com/cortexapps/brain-backend/pull/5057
> Fix: Post Initiatives revamp changes

- package.json
- src/api/types.ts
- src/components/EntityPage/EntityPage.test.tsx
- src/components/FilterCard/Filters.tsx
- src/components/Homepage/HomepageInsightCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeMetadataCard/InitiativeMetadataCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeStatsCard/InitiativeStatsCard.tsx
- src/components/Initiatives/InitiativesPage.test.tsx
- src/components/Initiatives/InitiativesPage/InitiativesList.tsx
- src/components/ReportsPage/Common/GroupByDropdown.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.test.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapUtils.ts
- src/components/Scorecards/ScorecardDetailsPage/ScorecardMetadataCard/ScorecardMetadataUtils.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardRuleExemptionsTab/ScorecardRuleExemptionsTab.tsx
- src/components/Scorecards/ScorecardsPage/ScorecardList.tsx
- src/utils/hooks.ts
- yarn.lock
**Merge to ui-revamp-feature branch!**
> Lint fixes

- CHANGELOG.md
- package.json
- src/components/ReportsPage/HeatmapPage/LevelsInfoCell.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/utils/ComponentUtils.ts
Add fallback for generating link when missing entity
Tested locally:
Without fix:
With fix:
> Add fallback for generating link when missing entity

- CHANGELOG.md
- README.md
- config.d.ts
- package.json
- src/components/CortexGroupActionItemsWidget/CortexGroupActionItemsWidget.test.tsx
- src/components/CortexGroupActionItemsWidget/CortexGroupActionItemsWidget.tsx
- src/components/CortexGroupActionItemsWidget/GroupComponentRuleInitiativeInfo.tsx
- src/components/CortexGroupActionItemsWidget/GroupComponentRuleInitiativesRow.tsx
- src/components/CortexLayout/CortexLayout.test.tsx
- src/components/CortexLayout/CortexLayout.tsx
- src/components/CortexPage/CortexPage.tsx
- src/components/Homepage/HomepageInsightCard.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitativeFilterDialog/InitiativeFilterDialog.tsx
- src/components/Initiatives/InitiativeDetailsPage/InitiativeDetailsPage.tsx
- src/components/Initiatives/InitiativesPage.test.tsx
- src/components/Initiatives/InitiativesPage/InitiativesList.tsx
- src/components/Initiatives/InitiativesPage/InitiativesPage.tsx
- src/components/ReportsPage/ProgressPage/AggregatedScorecardProgress.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceHeader.tsx
- src/components/Scorecards/ScorecardsServicePage/ScorecardsServiceProgress.tsx
- src/utils/hooks.ts
[[CET-6662](https://cortex1.atlassian.net/browse/CET-6662)] Backstage plugin customization
Add YAML settings to
- Change title and subtitle on Cortex page
- Hide links to Cortex app
- Rename "Initiatives"
Please test by setting values in YAML and checking the plugin respects the settings as I was not able to do this even for already implemented configuration (like `hideSettings`).
Here's example YAML (partial for this PR):
```yaml
cortex:
header:
title: 'My custom title'
subtitle: 'Custom subtitle'
hideCortexLinks: true
initiativeNameOverride:
singular: 'enhancement target'
plural: 'enhancement targets'
```
[CET-6662]: https://cortex1.atlassian.net/browse/CET-6662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CET-6662] Backstage plugin customization

- CHANGELOG.md
- package.json
- src/components/SettingsPage/SyncJobsTable.test.tsx
- src/components/SettingsPage/SyncJobsTable.tsx
https://cortex1.atlassian.net/browse/CET-5947
We want to replace "Few seconds ago" timestamps with real date and times.
> CET-5947 Display clearer timestamps

- CHANGELOG.md
- package.json
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
Fixes bug seen on this video:
[Screencast from 27.5.2024 14:24:57.webm](https://github.com/cortexapps/backstage-plugin/assets/32833929/14185326-6641-492d-9b9d-4fbfb54b1fb7)
> [Hotfix] Fix the row keys to correctly render Bird's eye report table

- .github/workflows/publish-gh-registry.yml
- package.json
- scripts/add_publish_to_github_config.sh
> Enable publishing to private git registry for debugging

- src/components/ReportsPage/HeatmapPage/HeatmapFilters.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
First part of hierarchy. Add simple drill down logic for both Teams and  Domain.
Fixes URL param parsing logic
https://www.loom.com/share/af515f871999475b886e864bcaf04c35
> Fix logic around URL parsing, add hierarchy drill down

- src/api/types.ts
- src/components/ReportsPage/HeatmapPage/HeatmapFilters.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByService.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableHeader.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
> Sorting for Birds Eye Report

- package.json
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByService.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
- yarn.lock
Rather than rendering all data elements we measure the area the table can take up, and then virtualize the table rendering only elements that can appear in the view.
> Virtualize Birds Eye Report

- CHANGELOG.md
- package.json
- src/api/CortexApi.ts
- src/api/CortexClient.ts
- src/api/types.ts
- src/api/userInsightTypes.ts
- src/components/ReportsPage/AllScorecardsPage/AllScorecardsPage.tsx
- src/components/ReportsPage/Common/GroupByDropdown.tsx
- src/components/ReportsPage/Common/HeaderTypeDropdown.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapCell.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapFilters.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapFiltersModal.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapFiltersSelect.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
- src/components/ReportsPage/HeatmapPage/HeatmapUtils.ts
- src/components/ReportsPage/HeatmapPage/LevelsInfoCell.tsx
- src/components/ReportsPage/HeatmapPage/SingleScorecardHeatmap.tsx
- src/components/ReportsPage/HeatmapPage/Tables/AllScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByGroup.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByLevels.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableByService.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HeatmapTableHeader.tsx
- src/components/ReportsPage/HeatmapPage/Tables/HierarchyBreadcrumbs.tsx
- src/components/ReportsPage/HeatmapPage/Tables/LevelsDrivenTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/SingleScorecardHeatmapTable.tsx
- src/components/ReportsPage/HeatmapPage/Tables/colorClasses.ts
- src/components/ReportsPage/ProgressPage/ProgressPage.tsx
- src/components/Scorecards/ScorecardDetailsPage/ScorecardDetailsPage.test.tsx
- src/utils/hooks.ts
- yarn.lock
[CET-6660] Backstage birdseye report parity with Cortex
~~Uses BE changes from this PR: https://github.com/cortexapps/brain-backend/pull/6583~~ (MERGED)
~~BEFORE MERGE, make sure #174 and #175 are merged into this, or otherwise resolved.~~ (resolved)
[CET-6660]: https://cortex1.atlassian.net/browse/CET-6660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CET-6660] Backstage birdseye report parity with Cortex

- CHANGELOG.md
- package.json
- src/components/ReportsPage/HeatmapPage/HeatmapFilters.tsx
Fix incorrect logic around group by changes and hierarchy
> Fix incorrect logic around group by changes and hierarchy

- CHANGELOG.md
- package.json
- src/components/ReportsPage/HeatmapPage/HeatmapPage.tsx
Measure when we have selected group bys
> Measure when we have selected group bys

- .github/workflows/publish.yml
Inline registry for yarn publish command
> Inline registry for yarn publish command

- .github/workflows/publish.yml
We have a problem to push the plugin package to the NPM registry. This PR comments the GitHub registry out in the `.npmrc` file in order to push to the default registry which is NPM.
> Fix NPM publishment

- .github/workflows/publish-gh-registry.yml
- .npmrc
- CHANGELOG.md
- package.json
- scripts/add_publish_to_github_config.sh
- yarn.lock
> Use Public Birdseye

- CHANGELOG.md
- package.json
- src/components/Initiatives/InitiativeCard/InitiativeCard.tsx
Initiatives with long descriptions should be truncated. Truncate to 10 lines, equal to scorecards. 
[CET-14109](https://cortex1.atlassian.net/browse/CET-14109)
[CET-14109]: https://cortex1.atlassian.net/browse/CET-14109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Truncate to 10 lines
